### ISSUE TITLE
malscc.de - Lighthouse Report

### ISSUE THREAD

**Issue by kleinlennart** [lukas-mertens/malscc#4]
Ich schätze mal als augenscheinlicher Perfektionist, der in seiner Facharbeit 90 Seiten über die Verbesserung seines neuronalen Netzes, statt der vorgegebenen 10 schreibt kannst du etwas mit konstruktiven Verbesserungsvorschlägen anfangen.

Persönlich versuche ich hiermit in Folge deines Open Source Appells meinen Beitrag zu leisten.
(und vielleicht kommt die Tage auch noch ein Pull request dazu ;D)
<br>

[Lighthouse Report Viewer](https://we.tl/t-syiFU5WkUL)

**Comment by lukas-mertens** [comment]
Vielen Dank! Ich werde mich darum kümmern, sobald ich Zeit dafür finde. MalSCC ist nur ein Nebenprojekt und ich bin aktuell in der Release-Phase meines derzeitigen Hauptprojektes, deshalb kann es noch 1-2 Wochen dauern, bis ich die entsprechenden Dinge verbessere. Zuerst werde ich aber eine ordentliche Readme schreiben und alles dokumentieren. Danke!

**Comment by kleinlennart** [comment]
Darf ich fragen, was dein derzeitiges Hauptprojekt ist?😉
